# TCL File Generated by Component Editor 9.0
# Sat Feb 06 18:03:27 EET 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | fft_sopc "fft_sopc" v1.0
# | null 2010.02.06.18:03:27
# | 
# | 
# | D:/ADC/asvm12120_fft_fast/Quartus/fast_fft/fft_sopc.v
# | 
# |    ./fft_sopc.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module fft_sopc
# | 
set_module_property NAME fft_sopc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME fft_sopc
set_module_property TOP_LEVEL_HDL_FILE fft_sopc.v
set_module_property TOP_LEVEL_HDL_MODULE fft_sopc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file fft_sopc.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink
# | 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink dataBitsPerSymbol 32
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink symbolsPerBeat 1

set_interface_property avalon_streaming_sink ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink sink_valid valid Input 1
add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink sink_data data Input 32
add_interface_port avalon_streaming_sink sink_error error Input 2
add_interface_port avalon_streaming_sink sink_ready ready Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source dataBitsPerSymbol 38
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source symbolsPerBeat 1

set_interface_property avalon_streaming_source ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source source_ready ready Input 1
add_interface_port avalon_streaming_source source_error error Output 2
add_interface_port avalon_streaming_source source_sop startofpacket Output 1
add_interface_port avalon_streaming_source source_eop endofpacket Output 1
add_interface_port avalon_streaming_source source_valid valid Output 1
add_interface_port avalon_streaming_source source_data data Output 38
# | 
# +-----------------------------------
