rule pcb (width 0.2)
rule pcb (clearance 0.2)
tax via 100
cost via 1
select all wires
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
bestsave on $\best.w
status_file $\progress.sts
unit mil
grid wire 1.000000 
grid via 25.000000 
rule pcb (width 7.9)
protect all wires
via_at_smd off
cost via high
